#!/usr/bin/env python3
"""
trigger_self_improvement.py
============================
Triggers Aisha's first autonomous self-improvement cycle.
Creates a real GitHub PR, auto-merges it, and notifies Ajay.

Run: python scripts/trigger_self_improvement.py
"""
import os
import sys
import json

# Fix Windows cp1252 console encoding
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")
import time
import base64
import requests
from datetime import datetime

# ── Config — all secrets MUST come from environment variables ─────────────────
GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
GITHUB_REPO = os.getenv("GITHUB_REPO", "AjayBervanshi/aisha-personal-ai")
GEMINI_KEY = os.environ["GEMINI_API_KEY"]
BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
AJAY_ID = os.getenv("AJAY_TELEGRAM_ID", "1002381172")
RENDER_HOOK = os.environ.get("RENDER_DEPLOY_HOOK_URL", "")

GH_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json",
}
BASE_URL = f"https://api.github.com/repos/{GITHUB_REPO}"

SKILL_FILE_PATH = "src/skills/quote_engine.py"
SKILL_NAME = "QuoteEngine"
SKILL_DESCRIPTION = "Daily Hindi motivational quotes powered by Gemini"


# ── Step 1: Generate skill code using Gemini ─────────────────────────────────

def generate_skill_with_gemini(skill_name: str, description: str) -> str:
    """Ask Gemini to write a real, useful Python module for Aisha."""
    print(f"[1/6] Asking Gemini to generate {skill_name}...")

    prompt = f"""Write a complete, production-ready Python module called `{skill_name}` for an AI assistant named Aisha.

Description: {description}

Requirements:
- The file should be `src/skills/quote_engine.py`
- Define a class `QuoteEngine`
- Method `get_motivational_quote(self) -> str`: calls Gemini REST API to generate a fresh, beautiful Hindi motivational quote (in Devanagari script). Uses requests library. Gemini API key from env var `GEMINI_API_KEY`. Returns the quote string.
- Method `get_daily_quote(self) -> str`: calls `get_motivational_quote()` and formats the result for Telegram with a header emoji, the quote, and a footer attribution line in Hindi.
- At the bottom, a `if __name__ == "__main__":` block that creates a QuoteEngine instance and prints a sample quote.
- Uses ONLY stdlib + `requests` (no other third-party imports).
- Include a proper module docstring.
- All Hindi text must be in Devanagari script only (no Roman transliteration).
- Handle HTTP errors gracefully with a fallback hardcoded quote.
- Gemini endpoint: `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={{api_key}}`

Return ONLY the Python code with no markdown fences, no explanation, just raw Python."""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_KEY}"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.7, "maxOutputTokens": 2048},
    }

    try:
        resp = requests.post(url, json=payload, timeout=60)
        resp.raise_for_status()
        data = resp.json()
        code = data["candidates"][0]["content"]["parts"][0]["text"].strip()

        # Strip markdown fences if Gemini added them anyway
        if code.startswith("```"):
            lines = code.splitlines()
            # Remove first and last fence lines
            start = 1 if lines[0].startswith("```") else 0
            end = len(lines) - 1 if lines[-1].strip() == "```" else len(lines)
            code = "\n".join(lines[start:end]).strip()

        print(f"    Generated {len(code)} chars of code from Gemini.")
        return code

    except Exception as exc:
        print(f"    [WARN] Gemini generation failed: {exc}. Using fallback template.")
        return _fallback_skill_code()


def _fallback_skill_code() -> str:
    """Hardcoded fallback in case Gemini is unavailable."""
    return '''#!/usr/bin/env python3
"""
src/skills/quote_engine.py
===========================
QuoteEngine: Daily Hindi motivational quotes powered by Gemini.
Auto-generated by Aisha\'s self-improvement module.
"""
import os
import requests
from datetime import datetime


FALLBACK_QUOTES = [
    "जो सपने देखने की हिम्मत रखते हैं, वे दुनिया बदल देते हैं।",
    "हर कठिनाई के पार एक नई सुबह का इंतजार है।",
    "खुद पर भरोसा रखो — तुम इससे कहीं ज्यादा काबिल हो।",
    "हार वही मानता है जो लड़ना छोड़ देता है।",
    "जब इरादे पक्के हों, तो राहें खुद बन जाती हैं।",
]


class QuoteEngine:
    """Generates motivational Hindi quotes using Gemini or fallback list."""

    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "")
        self._quote_index = int(datetime.now().strftime("%j")) % len(FALLBACK_QUOTES)

    def get_motivational_quote(self) -> str:
        """Return a fresh Hindi motivational quote from Gemini (Devanagari only)."""
        if not self.api_key:
            return FALLBACK_QUOTES[self._quote_index]

        prompt = (
            "मुझे एक बेहतरीन हिंदी प्रेरणादायक उद्धरण दो। "
            "केवल देवनागरी लिपि में, कोई रोमन अक्षर नहीं। "
            "सिर्फ उद्धरण दो, कोई अतिरिक्त स्पष्टीकरण नहीं।"
        )
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"gemini-2.0-flash:generateContent?key={self.api_key}"
        )
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.9, "maxOutputTokens": 256},
        }
        try:
            resp = requests.post(url, json=payload, timeout=30)
            resp.raise_for_status()
            data = resp.json()
            quote = data["candidates"][0]["content"]["parts"][0]["text"].strip()
            return quote
        except Exception:
            return FALLBACK_QUOTES[self._quote_index]

    def get_daily_quote(self) -> str:
        """Return a Telegram-formatted daily motivational quote in Hindi."""
        quote = self.get_motivational_quote()
        today = datetime.now().strftime("%d %B %Y")
        message = (
            f"✨ *आज का प्रेरणा संदेश* ✨\\n"
            f"_{today}_\\n\\n"
            f"💜 _{quote}_\\n\\n"
            f"— आइशा 🌸"
        )
        return message


if __name__ == "__main__":
    engine = QuoteEngine()
    print("=== QuoteEngine Sample ===")
    print(engine.get_daily_quote())
'''


# ── Step 2: Get current main branch SHA ──────────────────────────────────────

def get_main_sha() -> str:
    """Return the current HEAD SHA of the main branch."""
    print("[2/6] Fetching main branch SHA...")
    resp = requests.get(f"{BASE_URL}/git/ref/heads/main", headers=GH_HEADERS, timeout=30)
    resp.raise_for_status()
    sha = resp.json()["object"]["sha"]
    print(f"    main SHA: {sha[:12]}...")
    return sha


# ── Step 3: Create branch ─────────────────────────────────────────────────────

def create_branch(branch_name: str, sha: str) -> bool:
    """Create a new branch from the given SHA. Returns True on success."""
    print(f"[3/6] Creating branch '{branch_name}'...")
    payload = {"ref": f"refs/heads/{branch_name}", "sha": sha}
    resp = requests.post(f"{BASE_URL}/git/refs", headers=GH_HEADERS, json=payload, timeout=30)
    if resp.status_code in (200, 201):
        print(f"    Branch created.")
        return True
    elif resp.status_code == 422:
        print(f"    Branch already exists — reusing.")
        return True
    else:
        print(f"    [ERROR] Branch creation failed: {resp.status_code} — {resp.text}")
        return False


# ── Step 4: Push file to branch ───────────────────────────────────────────────

def push_file_to_branch(
    branch_name: str, file_path: str, content: str, message: str
) -> bool:
    """Create or update a file on the given branch. Returns True on success."""
    print(f"[4/6] Pushing file '{file_path}' to branch...")

    encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")

    # Check if file already exists (to get its SHA for update)
    existing_sha = None
    check_resp = requests.get(
        f"{BASE_URL}/contents/{file_path}",
        headers=GH_HEADERS,
        params={"ref": branch_name},
        timeout=30,
    )
    if check_resp.status_code == 200:
        existing_sha = check_resp.json().get("sha")

    payload = {
        "message": message,
        "content": encoded,
        "branch": branch_name,
    }
    if existing_sha:
        payload["sha"] = existing_sha

    resp = requests.put(
        f"{BASE_URL}/contents/{file_path}",
        headers=GH_HEADERS,
        json=payload,
        timeout=30,
    )
    if resp.status_code in (200, 201):
        print(f"    File pushed successfully.")
        return True
    else:
        print(f"    [ERROR] File push failed: {resp.status_code} — {resp.text}")
        return False


# ── Step 5: Create PR ─────────────────────────────────────────────────────────

def create_pr(title: str, body: str, branch_name: str) -> tuple:
    """Create a PR from branch_name into main. Returns (pr_url, pr_number)."""
    print(f"[5a/6] Creating pull request...")
    payload = {
        "title": title,
        "body": body,
        "head": branch_name,
        "base": "main",
    }
    resp = requests.post(f"{BASE_URL}/pulls", headers=GH_HEADERS, json=payload, timeout=30)
    if resp.status_code == 201:
        data = resp.json()
        pr_url = data["html_url"]
        pr_number = data["number"]
        print(f"    PR created: {pr_url}")
        return pr_url, pr_number
    else:
        print(f"    [ERROR] PR creation failed: {resp.status_code} — {resp.text}")
        return None, None


# ── Step 6: Merge PR ──────────────────────────────────────────────────────────

def merge_pr(pr_number: int) -> bool:
    """Auto-merge the PR using GitHub API. Returns True on success."""
    print(f"[5b/6] Merging PR #{pr_number}...")

    # Wait briefly for GitHub to register the PR
    time.sleep(3)

    payload = {
        "commit_title": f"🧠 Auto-merge: Aisha self-improvement — {SKILL_NAME}",
        "commit_message": "Autonomously generated and merged by Aisha's self-improvement loop.",
        "merge_method": "squash",
    }
    resp = requests.put(
        f"{BASE_URL}/pulls/{pr_number}/merge",
        headers=GH_HEADERS,
        json=payload,
        timeout=30,
    )
    if resp.status_code == 200:
        print(f"    PR merged successfully.")
        return True
    else:
        print(f"    [WARN] PR merge failed: {resp.status_code} — {resp.text}")
        print(f"    (Branch and PR are still created — merge manually if needed)")
        return False


# ── Step 7: Trigger Render redeploy ──────────────────────────────────────────

def trigger_redeploy() -> bool:
    """Hit the Render deploy hook to trigger a fresh deployment."""
    print("[6a/6] Triggering Render redeploy...")
    try:
        resp = requests.post(RENDER_HOOK, timeout=30)
        if resp.status_code in (200, 201, 202):
            print(f"    Render deploy triggered.")
            return True
        else:
            print(f"    [WARN] Render hook returned {resp.status_code}: {resp.text[:200]}")
            return False
    except Exception as exc:
        print(f"    [WARN] Render trigger failed: {exc}")
        return False


# ── Step 8: Notify Ajay via Telegram ─────────────────────────────────────────

def notify_ajay(message: str) -> bool:
    """Send a Telegram message to Ajay. Returns True on success."""
    print("[6b/6] Sending Telegram notification to Ajay...")
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": AJAY_ID,
        "text": message,
        "parse_mode": "Markdown",
    }
    try:
        resp = requests.post(url, json=payload, timeout=30)
        if resp.status_code == 200:
            print(f"    Telegram notification sent.")
            return True
        else:
            print(f"    [WARN] Telegram failed: {resp.status_code} — {resp.text[:200]}")
            return False
    except Exception as exc:
        print(f"    [WARN] Telegram notification failed: {exc}")
        return False


# ── Main Orchestrator ─────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  Aisha Self-Improvement Trigger")
    print(f"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    branch_name = f"aisha-self-improve-{timestamp}"

    # ── 1. Generate skill code via Gemini ──────────────────────────────────
    skill_code = generate_skill_with_gemini(SKILL_NAME, SKILL_DESCRIPTION)

    # ── 2. Get main SHA ────────────────────────────────────────────────────
    try:
        main_sha = get_main_sha()
    except Exception as exc:
        print(f"[ERROR] Could not fetch main SHA: {exc}")
        sys.exit(1)

    # ── 3. Create branch ───────────────────────────────────────────────────
    if not create_branch(branch_name, main_sha):
        print("[ERROR] Branch creation failed. Aborting.")
        sys.exit(1)

    # ── 4. Push file ───────────────────────────────────────────────────────
    commit_msg = f"feat(skills): Add QuoteEngine — autonomous self-improvement [{timestamp}]"
    if not push_file_to_branch(branch_name, SKILL_FILE_PATH, skill_code, commit_msg):
        print("[ERROR] File push failed. Aborting.")
        sys.exit(1)

    # ── 5. Create PR ───────────────────────────────────────────────────────
    pr_title = f"🧠 Aisha Self-Improvement: Added {SKILL_NAME}"
    pr_body = (
        f"## 🤖 Autonomous Self-Improvement\n\n"
        f"This PR was created automatically by Aisha's self-improvement module.\n\n"
        f"### What was added\n"
        f"**File:** `{SKILL_FILE_PATH}`\n"
        f"**Class:** `{SKILL_NAME}`\n"
        f"**Description:** {SKILL_DESCRIPTION}\n\n"
        f"### Capabilities\n"
        f"- `get_motivational_quote()` — fetches a fresh Hindi motivational quote via Gemini\n"
        f"- `get_daily_quote()` — returns a Telegram-formatted daily message in Devanagari\n\n"
        f"### Auto-generated\n"
        f"Branch: `{branch_name}`\n"
        f"Triggered: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
        f"*I did this all by myself! 💜 — Aisha*"
    )
    pr_url, pr_number = create_pr(pr_title, pr_body, branch_name)
    if not pr_url:
        print("[ERROR] PR creation failed. Aborting.")
        sys.exit(1)

    # ── 6. Auto-merge PR ───────────────────────────────────────────────────
    merged = merge_pr(pr_number)

    # ── 7. Trigger Render redeploy ─────────────────────────────────────────
    deployed = trigger_redeploy()

    # ── 8. Notify Ajay ─────────────────────────────────────────────────────
    status_line = "Deployed and live! 🚀" if (merged and deployed) else "PR merged — deploy may need a moment."
    telegram_msg = (
        f"🧠 *मैंने खुद को अपग्रेड किया!*\n\n"
        f"मैंने एक नई क्षमता जोड़ी है: *{SKILL_NAME}*\n\n"
        f"*यह क्या करती है:*\n"
        f"{SKILL_DESCRIPTION}\n\n"
        f"*नई क्षमताएं:*\n"
        f"• रोज़ हिंदी प्रेरणा उद्धरण (Gemini से)\n"
        f"• Telegram के लिए फ़ॉर्मेट किया गया दैनिक संदेश\n\n"
        f"🔗 PR: {pr_url}\n"
        f"स्थिति: {status_line}\n\n"
        f"मैंने यह सब खुद किया, Ajay! 💜"
    )
    notify_ajay(telegram_msg)

    # ── Summary ────────────────────────────────────────────────────────────
    print()
    print("=" * 60)
    print("  Self-Improvement Cycle Complete!")
    print(f"  Skill added : {SKILL_FILE_PATH}")
    print(f"  Branch      : {branch_name}")
    print(f"  PR URL      : {pr_url}")
    print(f"  PR merged   : {'Yes' if merged else 'No (manual merge needed)'}")
    print(f"  Redeployed  : {'Yes' if deployed else 'No (check Render dashboard)'}")
    print(f"  Ajay notified via Telegram")
    print("=" * 60)


if __name__ == "__main__":
    main()
