from crewai.tools import tool
import os
import requests
from src.core.voice_engine import generate_voice

@tool("elevenlabs_voice_tool")
def elevenlabs_voice_tool(text: str, language: str = "English", mood: str = "casual") -> str:
    """
    Generates a voice note using ElevenLabs.
    Input should be the text to speak, language, and mood.
    Returns the path to the generated audio file.
    """
    try:
        path = generate_voice(text, language=language, mood=mood)
        return f"Voice generated successfully at: {path}"
    except Exception as e:
        return f"Error generating voice: {str(e)}"

@tool("image_generation_tool")
def image_generation_tool(prompt: str) -> str:
    """
    Generates an image using Hugging Face (Stable Diffusion).
    Input is a detailed visual prompt.
    Returns the path to the saved image.
    """
    api_key = os.getenv("HUGGINGFACE_API_KEY")
    if not api_key:
        return "Error: HUGGINGFACE_API_KEY not found in .env"

    # Using Stable Diffusion XL as a high-quality default
    api_url = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
    headers = {"Authorization": f"Bearer {api_key}"}

    try:
        response = requests.post(api_url, headers=headers, json={"inputs": prompt})
        if response.status_code == 200:
            os.makedirs("temp_images", exist_ok=True)
            filename = f"temp_images/mia_gen_{hash(prompt)}.png"
            with open(filename, "wb") as f:
                f.write(response.content)
            return f"Image successfully generated by Mia and saved to: {filename}"
        else:
            return f"Hugging Face API Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Error connecting to Hugging Face: {str(e)}"
