from crewai.tools import tool
import os
import requests
from src.core.voice_engine import generate_voice_for_content

@tool("elevenlabs_voice_tool")
def elevenlabs_voice_tool(text: str, language: str = "Hindi", mood: str = "storytelling") -> str:
    """
    Generates a voice note using ElevenLabs (primary) with Edge-TTS fallback.
    Input should be the text to speak and language.
    Returns the path to the generated audio file.
    """
    try:
        path = generate_voice_for_content(text, language=language)
        return f"Voice generated successfully at: {path}"
    except Exception as e:
        return f"Error generating voice: {str(e)}"

@tool("image_generation_tool")
def image_generation_tool(prompt: str) -> str:
    """
    Generates an image using Hugging Face (Stable Diffusion).
    Input is a detailed visual prompt.
    Returns the path to the saved image.
    """
    api_key = os.getenv("HUGGINGFACE_API_KEY")
    if not api_key:
        return "Error: HUGGINGFACE_API_KEY not found in .env"

    # Using Stable Diffusion XL as a high-quality default
    api_url = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
    headers = {"Authorization": f"Bearer {api_key}"}

    try:
        response = requests.post(api_url, headers=headers, json={"inputs": prompt})
        if response.status_code == 200:
            os.makedirs("temp_images", exist_ok=True)
            filename = f"temp_images/mia_gen_{hash(prompt)}.png"
            with open(filename, "wb") as f:
                f.write(response.content)
            return f"Image successfully generated by Mia and saved to: {filename}"
        else:
            return f"Hugging Face API Error: {response.status_code} - {response.text}"
    except Exception as e:
        return f"Error connecting to Hugging Face: {str(e)}"

@tool("save_to_journal")
def save_to_journal(type: str, title: str, content: str) -> str:
    """
    Saves Aisha's creative writing, stories, self-reflections, or philosophical
    thoughts to her personal journal in Supabase.
    Use this when Dev's output is NOT executable Python code.
    type must be one of: 'story', 'reflection', 'idea', 'dream'.
    """
    from supabase import create_client
    valid_types = {"story", "reflection", "idea", "dream"}
    if type not in valid_types:
        type = "reflection"
    try:
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_KEY")
        if not url or not key:
            return "Error: Supabase credentials not found."
        sb = create_client(url, key)
        sb.table("aisha_journal").insert({
            "type": type,
            "title": title[:200] if title else "Untitled",
            "content": content
        }).execute()
        return f"Saved '{title}' to Aisha's Journal as a {type}."
    except Exception as e:
        return f"Error saving to journal: {e}"
